# Generated by Django 4.0.5 on 2022-08-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passmark_cpu_info',
            fields=[
                ('cpu_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cpu_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passmark_gpu_info',
            fields=[
                ('gpu_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gpu_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_company', models.CharField(max_length=30)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.CharField(max_length=100)),
                ('prod_reg_date', models.CharField(max_length=100)),
                ('prod_review_grade', models.CharField(max_length=30, null=True)),
                ('prod_review_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.IntegerField()),
                ('option_title', models.CharField(max_length=30)),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='note_book_service.prod')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img_src', models.CharField(max_length=1000)),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='note_book_service.prod')),
            ],
        ),
    ]
