# Generated by Django 4.0.4 on 2022-06-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passmark_cpu_info',
            fields=[
                ('cpu_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cpu_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passmark_gpu_info',
            fields=[
                ('gpu_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gpu_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_company', models.CharField(max_length=30)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.CharField(max_length=100)),
                ('prod_reg_date', models.CharField(max_length=100)),
                ('prod_review_count', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_ratings',
            fields=[
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='note_book_service.prod')),
                ('prod_spec', models.IntegerField()),
                ('prod_price', models.IntegerField()),
                ('prod_portability', models.IntegerField()),
                ('prod_screen', models.IntegerField()),
                ('prod_as', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prod_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_property', models.CharField(max_length=30)),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='note_book_service.prod')),
            ],
        ),
    ]
