# Generated by Django 4.0.4 on 2022-06-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_book_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod_ratings',
        ),
    ]
