# Generated by Django 4.0.5 on 2022-08-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_book_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='prod_review_count',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='prod_review_grade',
        ),
    ]
