# Generated by Django 4.0.4 on 2022-06-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_book_service', '0002_delete_prod_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='prod_review_grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
