# Generated by Django 4.0.4 on 2022-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_book_service', '0004_alter_prod_prod_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='prod_review_count',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
